"""e3 orders

Revision ID: 05abfb5056fd
Revises: 724553f6ce4f
Create Date: 2026-08-29 17:05:54.763677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05abfb5056fd'
down_revision = '724553f6ce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('created', 'confirmed', 'cancelled', 'failed', name='order_status'), nullable=False),
    sa.Column('fulfillment_type', sa.Enum('delivery', 'pickup', name='order_fulfillment_type'), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'apple_pay', 'gateway_stub', name='order_payment_method'), nullable=False),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('name_ar_snapshot', sa.String(length=160), nullable=False),
    sa.Column('image_path_snapshot', sa.String(length=255), nullable=True),
    sa.Column('base_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_lines_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_order_id'), ['order_id'], unique=False)

    op.create_table('order_line_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('group_id_snapshot', sa.Integer(), nullable=False),
    sa.Column('group_name_ar_snapshot', sa.String(length=120), nullable=False),
    sa.Column('group_kind_snapshot', sa.String(length=20), nullable=False),
    sa.Column('option_id_snapshot', sa.Integer(), nullable=False),
    sa.Column('option_name_ar_snapshot', sa.String(length=120), nullable=False),
    sa.Column('price_delta_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_line_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_line_selections_order_line_id'), ['order_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_line_selections_order_line_id'))

    op.drop_table('order_line_selections')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_lines_item_id'))

    op.drop_table('order_lines')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))

    op.drop_table('orders')
    # ### end Alembic commands ###
