"""e8 notifications

Revision ID: 486a0a541b1d
Revises: 12787600e1f0
Create Date: 2026-08-29 18:26:01.962067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '486a0a541b1d'
down_revision = '12787600e1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', 'web', name='device_platform'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_token'), ['token'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.String(length=160), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('target', sa.Enum('all', 'inactive_30d', 'has_ordered', name='notification_target'), nullable=False),
    sa.Column('target_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sent_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'customer_id', name='uq_notification_deliveries_pair')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_notification_id'), ['notification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_customer_id'))

    op.drop_table('notification_deliveries')
    op.drop_table('notifications')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_phone'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_customer_id'))

    op.drop_table('device_tokens')
    # ### end Alembic commands ###
