"""e5 loyalty tables + order columns

Revision ID: 5532110864f7
Revises: beb9a36d3739
Create Date: 2026-08-29 17:32:53.859960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5532110864f7'
down_revision = 'beb9a36d3739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('points_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('loyalty_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_per_riyal', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('riyal_per_point', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('min_redeem_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('earned', 'redeemed', 'adjustment', name='loyalty_ledger_reason'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_ledger_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('points_redeemed', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_column('points_earned')
        batch_op.drop_column('points_redeemed')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('loyalty_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_ledger_order_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_ledger_customer_id'))

    op.drop_table('loyalty_ledger')
    op.drop_table('loyalty_settings')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))

    op.drop_table('customers')
    # ### end Alembic commands ###
