"""e2 cross-sell links

Revision ID: 724553f6ce4f
Revises: 8da784ad88bc
Create Date: 2026-08-29 16:46:46.046160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724553f6ce4f'
down_revision = '8da784ad88bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_cross_sells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('recommended_item_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('item_id <> recommended_item_id', name='ck_item_cross_sells_no_self'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'recommended_item_id', name='uq_item_cross_sells_pair')
    )
    with op.batch_alter_table('item_cross_sells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_cross_sells_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_cross_sells_recommended_item_id'), ['recommended_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_cross_sells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_cross_sells_recommended_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_cross_sells_item_id'))

    op.drop_table('item_cross_sells')
    # ### end Alembic commands ###
