"""orders: add customer rating fields

Revision ID: 7be0571769cd
Revises: e821e6634320
Create Date: 2026-09-08 12:13:33.495049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be0571769cd'
down_revision = 'e821e6634320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('rating_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rating_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating_submitted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('rating_submitted_at')
        batch_op.drop_column('rating_comment')
        batch_op.drop_column('rating_tags')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
